import Fluent

/// Creates the saved-view and collaboration records used by the workspace.
/// Cascading task and board references keep deleted workspaces from leaving orphans.
struct CreateWorkspaceFeatures: AsyncMigration {
    func prepare(on database: any Database) async throws {
        let viewType = try await database.enum("board_view_type")
            .case("board")
            .case("table")
            .case("calendar")
            .case("gallery")
            .create()
        let memberRole = try await database.enum("board_member_role")
            .case("viewer")
            .case("commenter")
            .case("editor")
            .case("admin")
            .create()
        let taskStatus = try await database.enum("task_status").read()
        let taskPriority = try await database.enum("task_priority").read()

        try await database.schema(BoardView.schema)
            .id()
            .field("board_id", .uuid, .required, .references(Board.schema, "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("type", viewType, .required)
            .field("position", .int, .required)
            .field("configuration", .json)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()

        try await database.schema(BoardMember.schema)
            .id()
            .field("board_id", .uuid, .required, .references(Board.schema, "id", onDelete: .cascade))
            .field("user_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("role", memberRole, .required)
            .field("created_at", .datetime)
            .unique(on: "board_id", "user_id")
            .create()

        try await database.schema(TaskComment.schema)
            .id()
            .field("task_id", .uuid, .required, .references(Task.schema, "id", onDelete: .cascade))
            .field("author_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("body", .string, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .create()

        try await database.schema(ChecklistItem.schema)
            .id()
            .field("task_id", .uuid, .required, .references(Task.schema, "id", onDelete: .cascade))
            .field("title", .string, .required)
            .field("is_completed", .bool, .required, .sql(.default(false)))
            .field("position", .int, .required)
            .field("created_at", .datetime)
            .create()

        try await database.schema(TaskAttachment.schema)
            .id()
            .field("task_id", .uuid, .required, .references(Task.schema, "id", onDelete: .cascade))
            .field("uploaded_by_id", .uuid, .required, .references(User.schema, "id", onDelete: .cascade))
            .field("file_name", .string, .required)
            .field("storage_name", .string, .required)
            .field("content_type", .string, .required)
            .field("byte_count", .int, .required)
            .field("created_at", .datetime)
            .create()

        try await database.schema(TaskTemplate.schema)
            .id()
            .field("board_id", .uuid, .required, .references(Board.schema, "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("title", .string, .required)
            .field("description", .string)
            .field("status", taskStatus, .required)
            .field("priority", taskPriority, .required)
            .field("labels", .json, .required)
            .field("is_default", .bool, .required, .sql(.default(false)))
            .field("created_at", .datetime)
            .create()
    }

    func revert(on database: any Database) async throws {
        try await database.schema(TaskTemplate.schema).delete()
        try await database.schema(TaskAttachment.schema).delete()
        try await database.schema(ChecklistItem.schema).delete()
        try await database.schema(TaskComment.schema).delete()
        try await database.schema(BoardMember.schema).delete()
        try await database.schema(BoardView.schema).delete()
        try await database.enum("board_member_role").delete()
        try await database.enum("board_view_type").delete()
    }
}
